cart/urls.py
"""Cart routing module.
"""
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from news.views import NewsListView


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('tinymce/', include('tinymce.urls')),
    path('blog/', include('news.urls', namespace='news')),
    path('news-list/', NewsListView.as_view(), name='news_list'),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    # path("cookies/", include("cookie_consent.urls")),
    path('shop', include('shop.urls', namespace='shop')),
    path('home/', include('pages.urls', namespace='pages')),
    path('sitemap.xml', sitemap, name='sitemap-xml'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

coupons/urls.py
"""Coupons application routing module.
"""
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
"""Order routing module.
"""
from django.urls import path
from . import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
         name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf,
         name='admin_order_pdf'),
    path('order/<int:order_id>/pdf/', views.order_pdf, name='order_pdf'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
]

shop/urls.py
"""Shop routing module."""
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:product_id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

cart/models.py
"""Cart model.
"""
# from django.db import models
# Create your models here.

cart/forms.py
"""Cart form module.
"""
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """Form to add product.
    """
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
"""Cart views module.
"""
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from shop.models import Product
from shop.recommender import Recommender
from coupons.forms import CouponApplyForm
from .cart import Cart
from .forms import CartAddProductForm


@login_required
@require_POST
def cart_add(request, product_id):
    """Add product to cart.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@login_required
@require_POST
def cart_remove(request, product_id):
    """Remove item from cart.
    """
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


@login_required
def cart_detail(request):
    """Get items from cart.
    """
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
                            'quantity': item['quantity'],
                            'override': True})

    coupon_apply_form = CouponApplyForm()
    recommender = Recommender()
    cart_products = [item['product'] for item in cart]

    if cart_products:
        recommended_products = recommender.suggest_products_for(cart_products,
                                                                max_results=4)
    else:
        recommended_products = []

    return render(request,
                  'cart/cart_detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form,
                   'recommended_products': recommended_products})

templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Panier
{% endblock %}

{% block content %}
  <h1>Votre panier</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Produit</th>
        <th>Quantité</th>
        <th>Supprimer</th>
        <th>Prix unitaire(€)</th>
        <th>Prix</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Mettre à jour">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="Supprimer">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">€{{ item.price }}</td>
            <td class="num">€{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}

      {% if cart.coupon %}
        <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="4"></td>
          <td class="num">€{{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            "{{ cart.coupon.code }}" coupon ({{ cart.coupon.discount }}% de remise)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - €{{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}

      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">
          €{{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>

    </tbody>
  </table>
  
  {% if recommended_products %}
    <div class="recommendations cart">
      <h2 class="fs-3">Les clients qui ont acheté ce produit ont aussi aimé</h2>
      {% for p in recommended_products %}
        <div class="item">
          <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}
            {% static 'img/no_image.png' %}{% endif %}">
          </a>
          <p><a href="{{ p.get_absolute_url }}">{{ p.name }}: €{{ p.price }}</a></p>
        </div>
      {% endfor %}
    </div>
  {% endif %}

  <div class="d-flex align-content-around align-items-end flex-column">
    <p class="mb-4">Utiliser une réduction:</p>
    <form id="code-form" action="{% url 'coupons:apply' %}" method="post">
      {{ coupon_apply_form }}
      <input type="submit" value="Utiliser">
      {% csrf_token %}
    </form>

    <p class="text-right">
      <a href="{% url 'shop:product_list' %}" class="button
      light">Continuer le shopping</a>
      <a href="{% url 'orders:order_create' %}" class="button">Payer</a>
    </p>
  </div>

{% endblock %}