cart/urls.py
"""Cart routing module.
"""
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from news.views import NewsListView


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('tinymce/', include('tinymce.urls')),
    path('blog/', include('news.urls', namespace='news')),
    path('news-list/', NewsListView.as_view(), name='news_list'),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    # path("cookies/", include("cookie_consent.urls")),
    path('shop', include('shop.urls', namespace='shop')),
    path('home/', include('pages.urls', namespace='pages')),
    path('sitemap.xml', sitemap, name='sitemap-xml'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

pages/urls.py
"""Pages routing module.
"""
from django.urls import path
from .views import (HomePageView, CGUPageView, PartnersPageView, CGVPageView,
                    LegalNoticesView, AboutPageView, GPDRPageView)

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('cgu/', CGUPageView.as_view(), name='cgu'),
    path('cgv/', CGVPageView.as_view(), name='cgv'),
    path('rgpd/', GPDRPageView.as_view(), name='rgpd'),
    path('partenaires/', PartnersPageView.as_view(), name='partners'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('mentions-legales/', LegalNoticesView.as_view(), name='mentions'),
]

shop/urls.py
"""Shop routing module."""
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:product_id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

users/urls.py
"""Routing module.
"""
from django.urls import path, re_path
from django.views.decorators.cache import cache_page
from . import views

app_name = "users"

urlpatterns = [
    path('', views.sign_in, name='sign-in'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('sign-out/', views.sign_out, name='sign-out'),
    path('forgotten-password/', views.forgotten_password,
         name='forgotten-password'),
    path('users/email/', views.email, name='email'),
    path('account/', views.account, name='account'),
    re_path(r'^verification/(?P<uidb64>.+)/(?P<token>.+)/$',
            views.verification, name='verification'),
    path('news/',
        views.UserNewsListView.as_view(),
        name='user_news_list'),
    path('news/<pk>/',
        cache_page(60 * 15)(views.UserNewsDetailView.as_view()),
        name='user_news_detail'),
    path('news/<pk>/<module_id>/',
        cache_page(60 * 15)(views.UserNewsDetailView.as_view()),
        name='user_news_detail_module'),
]

templates/_footer.html
{% load static %}

{% block footer %}
  <div class="mt-5 pt-5 pb-5 footer d-flex flex-column">
    <div class="footer-block-1 d-flex flex-row justify-content-around align-items-center">
      <div class="footer-title d-flex flex-column justify-content-center align-items-center">  
        <h2><strong>LML Events</strong></h2>
        <p class="pr-5 text-white-50">Plongez dans une nouvelle réalité !</p>
      </div>
      <div class="d-flex footer-social justify-content-around align-items-center flex-column">
        <h3>Nous suivre:</h3>
        <p>
          <a href="https://www.linkedin.com/in/lml-events/"><i class="fab fa-linkedin-in fa-xl"></i></a>
          <a href="https://discord.com/channels/@me/1072852473196314697/1107936011645886535"><i class="fab fa-facebook fa-xl"></i></a>
          <a href="https://twitter.com/lmlevents49/"><i class="fab fa-twitter fa-xl"></i></a>
          <a href="https://instagram.com/lmlevents49?igshid=NTc4MTIwNjQ2YQ=="><i class="fab fa-instagram fa-xl"></i></a>
          <a href="#"><i class="fab fa-twitch fa-xl"></i></a>
          <a href="#"><i class="fab fa-tiktok fa-xl"></i></a>
          <a href="#"><i class="fab fa-youtube fa-xl"></i></a>
        </p>
      </div>
    </div>

    <div class="footer-block-2 d-flex flex-row justify-content-around align-items-stretch mt-3">
      <div class="f-menu">
        <h4 class="f-menu-title">Liens</h4>
          <ul class="m-0 p-0 f-menu-list list-unstyled">
            <li><a class="f-link" href="{% url 'pages:rgpd' %}">RGPD</a></li>
            <li><a class="f-link" href="{% url 'pages:cgu' %}">CGU</a></li>
            <li><a class="f-link" href="{% url 'pages:cgv' %}">CGV</a></li>
            <li><a class="f-link" href="{% url 'pages:mentions' %}">Mentions légales</a></li>
            <li><a class="f-link" href="{% url 'pages:partners' %}">Partenaires</a></li>
          </ul>
      </div>
      <div class="location">
        <h4 class="f-menu-loc">Localisation</h4>
        <p>Centre Pierre Cointreau CCI</p>
        <p>132 Avenue de Lattre de Tassigny</p>
        <p>49000 Angers</p>
        <p class="mb-0"><i class="fa fa-phone mr-3"></i>  (+33)7 77 77 71 45</p>
        <p class="mb-0"><i class="fa-regular fa-paper-plane mr-3"></i><a href="mailto:contact.lmlevents49@gmail.com">  contact</a></p>
      </div>
    </div>

    <div class="footer-block-3 d-flex flex-row">
      <div class="col copyright">
        <p><small class="text-white-50">© {% now "Y" %}. All Rights Reserved. Version {{ APP_VERSION_NUMBER }}.</small></p>
      </div>
    </div>
  </div>
{% endblock footer %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}LML Event shop{% endblock %}</title>
    <link rel="stylesheet" 
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
          crossorigin="anonymous">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
  </head>

  <body>

    <div id="header" class="header d-flex justify-content-between" style="{height: 15% !important; padding: 0 10%;}">

      <div class="logo-block h-10 w-25 pb-2" class="flex-shrink-0">
        <a href="/" class="logo">
          <img class="img-fluid img-logo" src="{% static 'img/logo.png' %}" alt="Logo">
        </a>
      </div>

      <div class="top-menu" class="flex-shrink-1">
        {% if user.is_authenticated %}
          <a href="{% url 'users:account' %}"><i class="fa-regular fa-circle-user" style="color: #ebf2ff;"></i></a>
          <a href="{% url 'users:sign-out' %}"><i class="fa-solid fa-right-from-bracket"></i></a>
        {% else %}
          <a href="{% url 'users:sign-in' %}"><i class="fa-regular fa-right-to-bracket"></i></a>
          <a href="{% url 'users:sign-up' %}"><i class="fa-regular fa-user-plus"></i></a>
        {% endif %}
      </div>

    </div>

    <div id="subheader" class="subheader d-flex justify-content-between">

      <div class="nav">
        <a class="nav-link" href="{% url 'pages:home' %}">Accueil</a>  <p class="sep">|</p>
        <a class="nav-link" href="{% url 'shop:product_list' %}">Boutique</a>  <p class="sep">|</p>
        <a class="nav-link" href="{% url 'news_list' %}">Actualités</a>  <p class="sep">|</p>
        <a class="nav-link" href="{% url 'pages:about' %}">About</a>
      </div>

      <div class="cart mr-2">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            <a href="{% url 'cart:cart_detail' %}" class="cart-icon position-relative d-inline-flex" aria-label="Détail de votre panier">
              €{{ cart.get_total_price }}&nbsp;&nbsp;
              <i class="fa-solid fa-cart-shopping"></i>
              <span class="cart-basket d-flex align-items-center justify-content-center">
                {{ total_items }}
              </span>
            </a>
          {% elif not order %}
            <i class="fa-solid fa-cart-shopping"></i>
          {% endif %}
        {% endwith %}
      </div>

    </div>

    <div id="content">

      {% block content %}
      {% endblock content %}

    </div>

    {% include "_footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
            crossorigin="anonymous"></script>

  </body>
</html>

templates/order_created.html
{% extends "base.html" %}

{% block title %}
  Thank you
{% endblock %}

{% block content %}
  <h1>Thank you</h1>
  <p>Your order has been successfully completed. Your order number is
  <strong>{{ order.id }}</strong>.</p>
{% endblock %}