cart/urls.py
"""Cart routing module.
"""
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from news.views import NewsListView


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('tinymce/', include('tinymce.urls')),
    path('blog/', include('news.urls', namespace='news')),
    path('news-list/', NewsListView.as_view(), name='news_list'),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    # path("cookies/", include("cookie_consent.urls")),
    path('shop', include('shop.urls', namespace='shop')),
    path('home/', include('pages.urls', namespace='pages')),
    path('sitemap.xml', sitemap, name='sitemap-xml'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

orders/urls.py
"""Order routing module.
"""
from django.urls import path
from . import views


app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,
         name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf,
         name='admin_order_pdf'),
    path('order/<int:order_id>/pdf/', views.order_pdf, name='order_pdf'),
    path('order/<int:order_id>/', views.order_detail, name='order_detail'),
]

shop/urls.py
"""Shop routing module."""
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:product_id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

users/urls.py
"""Routing module.
"""
from django.urls import path, re_path
from django.views.decorators.cache import cache_page
from . import views

app_name = "users"

urlpatterns = [
    path('', views.sign_in, name='sign-in'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('sign-out/', views.sign_out, name='sign-out'),
    path('forgotten-password/', views.forgotten_password,
         name='forgotten-password'),
    path('users/email/', views.email, name='email'),
    path('account/', views.account, name='account'),
    re_path(r'^verification/(?P<uidb64>.+)/(?P<token>.+)/$',
            views.verification, name='verification'),
    path('news/',
        views.UserNewsListView.as_view(),
        name='user_news_list'),
    path('news/<pk>/',
        cache_page(60 * 15)(views.UserNewsDetailView.as_view()),
        name='user_news_detail'),
    path('news/<pk>/<module_id>/',
        cache_page(60 * 15)(views.UserNewsDetailView.as_view()),
        name='user_news_detail_module'),
]

users/models.py
"""Users model.
"""
from django.db import models
from django.contrib.auth.models import User
from .choices import COUNTRIES


class UserProfile(models.Model):
    '''Our UserProfile model extends the built-in Django User Model.
    '''
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telephone = models.CharField(max_length=15, null=True, blank=True)
    address = models.CharField(verbose_name="Addresse", max_length=100,
                               null=True, blank=True)
    town = models.CharField(verbose_name="Ville", max_length=100,
                            null=True, blank=True)
    county = models.CharField(verbose_name="Région", max_length=100,
                              null=True, blank=True)
    post_code = models.CharField(verbose_name="Code Postale", max_length=8,
                                 null=True, blank=True)
    country = models.CharField(verbose_name="Pays", max_length=100,
                               null=True, blank=True, choices=COUNTRIES)
    is_active = models.BooleanField(default=True)

    email_verified = models.BooleanField(default=False)
    two_step_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.user}'


class UserToken(models.Model):
    '''Our UserToken model is used to store verification tokens generated
    by users.
    '''
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=100, null=True, blank=True)
    two_step_code = models.CharField(max_length=6, null=True, blank=True)
    # Used to change the object type
    is_email = models.BooleanField(default=False)
    is_password = models.BooleanField(default=False)
    is_sms = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.user}'

users/views.py
"""Views module.
"""
import json
from django.conf import settings
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect, reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from orders.models import Order
from news.models import News

from .models import UserToken
from .mixins import (
    form_errors,
    redirect_params,
    TokenGenerator,
    ActivateTwoStep,
    CreateEmail)
from .forms import (
    UserForm,
    UserProfileForm,
    ForgottenPasswordForm,
    AuthForm,
    RequestPasswordForm,
    TwoStepForm)

MESSAGE = "Un incident est survenu. Vérifiez et réessayez !"
ERR = "error"
OK = "perfect"


def sign_up(request):
    '''Basic view for user sign up
    '''
    # Redirect if user is already signed in
    if request.user.is_authenticated:
        return redirect(reverse('users:sign-up'))

    user_form = UserForm()
    userprofile_form = UserProfileForm()
    result = ERR
    message = MESSAGE
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    # Safe guard to stop sign up until API key is added
    if settings.TWILIO_TOKEN == "XXX":
        return HttpResponse(
            json.dumps({"result": result, "message": message}),
            content_type="application/json")

    if is_ajax and request.method == "POST":
        user_form = UserForm(data=request.POST)
        userprofile_form = UserProfileForm(data=request.POST)

        # If both forms are valid, do something
        if user_form.is_valid() and userprofile_form.is_valid():
            user = user_form.save()

            # Commit = False is used as userprofile.user can not be null
            userprofile = userprofile_form.save(commit=False)
            userprofile.user = user
            userprofile.save()

            # Mark user profile as inactive until verified
            user.is_active = False
            user.email = user.username
            user.save()

            # Create a new token
            token = TokenGenerator()
            make_token = token.make_token(user)
            url_safe = urlsafe_base64_encode(force_bytes(user.pk))

            # Create and sends a SMS code
            sms_code = ActivateTwoStep(user=user, token=make_token)

            result = OK
            message = "Nous vous avons envoyé un SMS."
            context = {
                "result": result,
                "message": message,
                "url_safe": url_safe,
                "token": make_token
                }
        else:
            message = form_errors(user_form, userprofile_form)
            context = {"result": result, "message": message}

        return HttpResponse(
            json.dumps(context),
            content_type="application/json")

    context = {'u_form': user_form, 'up_form': userprofile_form}
    return render(request, 'users/sign_up.html', context)


def sign_in(request):
    '''Basic view for user sign in.
    '''
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
    # Redirect if user is already signed in
    if request.user.is_authenticated:
        return redirect(reverse('users:account'))

    auth_form = AuthForm()
    result = ERR
    message = MESSAGE

    if is_ajax and request.method == "POST":
        auth_form = AuthForm(data=request.POST)

        if auth_form.is_valid():
            username = auth_form.cleaned_data.get('username')
            password = auth_form.cleaned_data.get('password')
            # Authenticate Django built in authenticate -
            # https://docs.djangoproject.com/en/3.1/ref/contrib/auth/
            user = authenticate(request, username=username, password=password)

            if user is not None:

                # Check to see if 2-step verification is active
                if user.userprofile.two_step_active:
                    # Create and sends a SMS code
                    token = TokenGenerator()
                    make_token = token.make_token(user)
                    url_safe = urlsafe_base64_encode(force_bytes(user.pk))
                    # Create and sends a SMS code
                    sms_code = ActivateTwoStep(user=user, token=make_token)
                    message = 'Nous vous avons envoyé un SMS'
                    result = OK
                    return HttpResponse(
                        json.dumps(
                            {"result": result,
                             "message": message,
                             "url_safe": url_safe,
                             "token": make_token}),
                        content_type="application/json")

                login(request, user)
                message = 'Vous êtes connecté'
                result = OK

        else:
            message = form_errors(auth_form)

        return HttpResponse(
            json.dumps({"result": result, "message": message}),
            content_type="application/json")

    context = {'a_form': auth_form}

    # Passes 'token_error' parameter to url to handle a error message
    token_error = request.GET.get("token_error", None)

    if token_error:
        context["token_error"] = "true"
    else:
        context["token_error"] = "false"

    return render(request, 'users/sign_in.html', context)


def sign_out(request):
    '''Basic view for user sign out.
    '''
    logout(request)
    return redirect(reverse('users:sign-in'))


def forgotten_password(request):
    '''Basic view for users to request a new password.
    '''
    rp_form = RequestPasswordForm()
    result = ERR
    message = MESSAGE
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

    if is_ajax and request.method == "POST":
        rp_form = RequestPasswordForm(data=request.POST)

        if rp_form.is_valid():
            username = rp_form.cleaned_data.get('email')
            user = User.objects.get(username=username)
            # Create a new token
            token = TokenGenerator()
            make_token = token.make_token(user)

            user_token = UserToken.objects.create(
                user=user,
                token=make_token,
                is_password=True)

            # Send email verification email
            CreateEmail(
                request,
                email_account="donotreply",
                subject='Réinitialisation de votre mot de passe',
                email=user.username,
                cc=[],
                template="mail/password_email.html",
                token=make_token,
                url_safe=urlsafe_base64_encode(force_bytes(user.pk))
            )
            result = OK
            message = "Vous allez recevoir un mail pour réinitialiser " \
                      "votre mot de passe."
        else:
            message = form_errors(rp_form)

        return HttpResponse(
            json.dumps({"result": result, "message": message}),
            content_type="application/json")
    context = {'rp_form': rp_form}
    return render(request, 'users/forgotten_password.html', context)


@login_required
def account(request):
    '''Account view for registered users
    '''
    if request.method == "POST":
        toggle = request.POST.get("toggle")
        userprofile = request.user.userprofile

        if toggle == "on":
            userprofile.two_step_active = True
        else:
            userprofile.two_step_active = False

        userprofile.save()

        return HttpResponse(
            json.dumps({}),
            content_type="application/json")

    context = {}
    # TODO add an owner to Coupon model and add it to the context to
    # display it in the account template.
    # Passes 'verified' parameter to url to handle a success message
    verified = request.GET.get("verified", None)

    order_query = Order.objects.filter(email=request.user.email)
    context = {'invoices': order_query}

    if verified:
        context["verified"] = "true"
    else:
        context["verified"] = "false"

    return render(request, 'users/account.html', context)


@login_required
def email(request):
    '''AJAX function to request email view for registered users.
    '''
    result = ERR
    message = MESSAGE

    if request.method == "POST":
        user = request.user
        # Create a new token
        token = TokenGenerator()
        make_token = token.make_token(user)
        url_safe = urlsafe_base64_encode(force_bytes(user.pk))

        # Create a usertoken object to store token
        user_token = UserToken.objects.create(
            user=user,
            token=make_token,
            is_email=True)

        # Send email verification email
        CreateEmail(
            request,
            email_account="donotreply",
            subject='Vérifiez votre email',
            email=user.username,
            cc=[],
            template="mail/verification_email.html",
            token=make_token,
            url_safe=url_safe)

        result = OK
        message = "Nous vous avons envoyé un mail de vérification."
        return HttpResponse(
            json.dumps({"result": result, "message": message}),
            content_type="application/json")

    return HttpResponse(
        json.dumps({"result": result, "message": message}),
        content_type="application/json")


def verification(request, uidb64, token):
    '''Function view to handle verification tokens
    '''
    try:

templates/users/account.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="{% url 'users:account' %}">Compte utilisateur</a></li>
  <li><a href="{% url 'users:sign-out' %}">Déconnexion</a></li>
  <li><a href="{% url 'shop:product_list' %}">Boutique</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Profil utilisateur</h3>

<div class="container">

  <h4>Détail du compte utilisateur</h4>
  <table>
    <thead>
      <tr>
        <th>Champ</th>
        <th>Valeur</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Username</td>

        {% if request.user.userprofile.email_verified %}
          <td>{{request.user.username}} <b style="color:green">(vérifié)</b></td>
        {% else %}
          <td>{{request.user.username}} <a href="javascript:void(0)" onclick="EmailVerification()"><b style="color:red">(à vérifier)</b></a></td>
        {% endif %}
 
      </tr>
      <tr>
        <td>Nom</td>
        <td>{{request.user.first_name}} {{request.user.last_name}}</td>      
      </tr>
      <tr>
        <td>Téléphone</td>
        <td>{{request.user.userprofile.telephone}}</td>      
      </tr>
      <tr>
        <td>Addresse</td>
        <td>
          <address>
            {{request.user.userprofile.address}}<br>
            {{request.user.userprofile.town}}<br>
            {{request.user.userprofile.county}}<br>
            {{request.user.userprofile.post_code}}<br>
          </address>
        </td>      
      </tr>

      {% if request.user.userprofile.two_step_active %}
      <tr>
        <td id="2-step-term">Désactiver la double authentification</td>
        <td>  
          <label class="switch">
            <input id="2-step-toggle" type="checkbox" checked>
            <span class="slider round" onclick="Toggle()"></span>
          </label>
        </td>     
      </tr>
      {% else %}
      <tr>
        <td id="2-step-term">Activer la double authentification</td>
        <td>  
          <label class="switch">
            <input id="2-step-toggle" type="checkbox">
            <span class="slider round" onclick="Toggle()"></span>
          </label>
        </td>       
      </tr>
      {% endif %}


    </tbody>
  </table>

  <br>
  <h4>Historique des factures</h4>

  <table>
    <thead>
      <tr>
        <th>Factures</th>
        <th>Total € TTC</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for invoice in invoices %}
        <tr>
          <td><a href="{% url 'orders:order_pdf' invoice.pk %}">{{ invoice }}</a></td>
          <td>{{ invoice.get_total_cost }}</td>
          {% if invoice.paid %}
            <td>Payée</td>
          {% else %}
            <td><a href="{% url 'orders:order_detail' invoice.pk %}">Impayée</a></td>
          {% endif %}
        </tr>
      {% empty %}
        <tr>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      {% endfor %}
 
    </tbody>
  </table>
  {% comment %} <br />
  <h4>Bons de réduction</h4> {% endcomment %}
  {% comment %} <table>
    <thead>
      <tr>
        <th>Code</th>
        <th>Réductions</th>
        <th>Début de validité</th>
        <th>Fin de validité</th>
        <th>Etat</th>
      </tr>
    </thead>
    <tbody>
      <tr>

        {% for coupon in coupons %}
          <td>{{ coupon }}</td>
          <td>{{ coupon.discount }}</td>
          <td>{{ coupon.valid_from }}</td>
          <td>{{ coupon.valid_to }}</td>
          {% if coupon.active %}
            <td>Actif</td>
          {% else %}
            <td>Inactif</td>
          {% endif %}
        {% empty %}
          <td></td>
          <td></td>
          <td></td>
        {% endfor %}
 
      </tr>
    </tbody>
  </table> {% endcomment %}



</div>

<!-- This handels the verified url param & displays a success alert-->
<script type="text/javascript">
  let ver = "{{ verified|safe }}";
  if (ver == "true"){
    alert("Merci, votre email a été vérifié.");
  }
</script>

{% endblock %}

{% block extend_footer %}

{% endblock %}

templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  {% include 'users/partials/mixin.html' %}

  <title>LML Events</title>

  <!-- visit https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom to get script-->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />

  <!-- This allows us to extend the head scripts in HTML docs that have special requirements-->
  {% block extend_head %}

  {% endblock %}

</head>
<body>

  <!-- This allows us to extend the nav bar in HTML docs that have special requirements-->
  {% block extend_nav %}

  {% endblock %}

  <div class="div-container">
    
    {% block content %}

    {% endblock %}

  </div>

  <!--visit https://code.jquery.com/ for jquery script-->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

  <!-- This allows us to extend the foot scripts in HTML docs that have special requirements-->
  {% block extend_footer %}

  {% endblock %}

  <script src="{% static 'js/main.js' %}"></script>
  
</body>
</html>

templates/users/forgotten_password.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a href="{% url 'users:sign-in' %}">Connexion</a></li>
  <li><a href="{% url 'users:sign-up' %}">Création de compte</a></li>
  <li><a class="active" href="javascript:void(0)">Mot de passe oublié</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Mot de passe oublié</h3>

<div class="container">

  <form id="requestpasswordform" method="POST" action="/forgotten-password/">
    {% csrf_token %}
    <label for="email">Username</label>
    {{rp_form.email}}

    <button type="submit">Nouveau mot de passe</button>
  </form>

  {{rp_form.errors}}

</div>

{% endblock %}


{% block extend_footer %}

{% endblock %}

templates/users/sign_in.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="{% url 'users:sign-in' %}">Connexion</a></li>
  <li><a href="{% url 'users:sign-up' %}">Création de compte</a></li>
  <li><a href="{% url 'users:forgotten-password' %}">Mot de passe oublié</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Connexion</h3>

<div class="container">

  <form id="signinform" method="POST" action="/">
    {% csrf_token %}
    <label for="username">Username</label>
    {{a_form.username}}

    <label for="password">Password</label>
    {{a_form.password}}

    <label class="check-container">Montrer
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <button type="submit">Connexion</button>
 </form>

 {{a_form.errors}}

</div>

<!-- This handels the verified url param & displays a success alert-->
<script type="text/javascript">
  let token_error = "{{ token_error|safe }}";
  if (token_error == "true"){
    alert("Le token est incorrecte. Réessayez, s'il vous plaît !")
  }
</script>

{% endblock %}

{% block extend_footer %}

{% endblock %}

templates/users/sign_up.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}

{% block extend_nav %} 

<ul class="sidenav">
  <li><a href="{% url 'users:sign-in' %}">Connexion</a></li>
  <li><a class="active" href="{% url 'users:sign-up' %}">Créer un compte</a></li>
  <li><a href="{% url 'users:forgotten-password' %}">Mot de passe oublié</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Création de compte</h3>

<div class="container">


  <form id="signupform" method="POST" action="/sign-up/">
    {% csrf_token %}

    <label for="username">Username</label>
    {{u_form.username}}

    <label for="password1">Password</label>
    {{u_form.password1}}

    <label for="password2">Confirm Password</label>
    {{u_form.password2}}

    <label class="check-container">Montrer
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <label for="first_name">Prénom</label>
   {{u_form.first_name}}

   <label for="last_name">Nom</label>
   {{u_form.last_name}}

   <label for="address">Addresse</label>
   {{up_form.address}}

   <label for="town">Ville</label>
   {{up_form.town}}

   <label for="county">Région</label>
   {{up_form.county}}

   <label for="post_code">Code postale</label>
   {{up_form.post_code}}

   <label for="post_code">Pays</label>
   {{up_form.country}}

   <label for="telephone">Telephone</label>
   {{up_form.telephone}}

   <button type="submit">Créer</button>
 </form>

 {{u_form.errors}}
 {{up_form.errors}}

</div>

{% endblock %}

{% block extend_footer %}


{% endblock %}

templates/users/two_step_verification.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="javascript:void(0)">Double authentification</a></li>
  <li><a href="{% url 'users:sign-in' %}">Connexion</a></li>
  <li><a href="{% url 'users:sign-up' %}">Créer un compte</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Double authentification</h3>

<div class="container">

  <form id="twostepform" method="POST" action="/verification/{{uidb64}}/{{token}}/">
    {% csrf_token %}

    <label for="two_step_code">Code</label>
    {{ts_form.two_step_code}}

   <button type="submit">Vérifier</button>
 </form>

 {{ts_form.errors}}

</div>

{% endblock %}

{% block extend_footer %}


{% endblock %}

templates/users/verification.html
{% extends 'users/base.html' %}
{% load static %}


{% block extend_head %}

{% endblock %}


{% block extend_nav %}

<ul class="sidenav">
  <li><a class="active" href="javascript:void(0)">Mot de passe oublié</a></li>
  <li><a href="{% url 'users:sign-in' %}">Connexion</a></li>
  <li><a href="{% url 'users:sign-up' %}">Créer un mot de passe</a></li>
</ul>

{% endblock %}


{% block content %}

<h3>Réinitialisation du mot de passe</h3>

<div class="container">

  <form id="updatepasswordform" method="POST" action="/verification/{{uidb64}}/{{token}}/">
    {% csrf_token %}

    <label for="new_password1">Mot de passe</label>
    {{fp_form.new_password1}}

    <label for="new_password2">Confirmer</label>
    {{fp_form.new_password2}}

    <label class="check-container">Montrer
     <input type="checkbox" onclick="showPword()">
     <span class="checkmark"></span>
   </label>

   <button type="submit">Réinitialiser</button>
 </form>

 {{fp_form.errors}}

</div>

{% endblock %}

{% block extend_footer %}


{% endblock %}