cart/urls.py
"""Cart routing module.
"""
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

config/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from news.views import NewsListView


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('tinymce/', include('tinymce.urls')),
    path('blog/', include('news.urls', namespace='news')),
    path('news-list/', NewsListView.as_view(), name='news_list'),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    # path("cookies/", include("cookie_consent.urls")),
    path('shop', include('shop.urls', namespace='shop')),
    path('home/', include('pages.urls', namespace='pages')),
    path('sitemap.xml', sitemap, name='sitemap-xml'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

payment/urls.py
"""Payment routing module.
"""
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('completed/', views.payment_completed, name='completed'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

payment/views.py
"""Payment view module.
"""
from decimal import Decimal
import stripe
from django.conf import settings
from django.shortcuts import render, redirect, reverse,\
                             get_object_or_404
from orders.models import Order


# create the Stripe instance
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION


def payment_process(request):
    """Payment process.
    """
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)

    if request.method == 'POST':
        success_url = request.build_absolute_uri(
                        reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(
                        reverse('payment:canceled'))

        # Stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': []
        }

        # add order items to the Stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'eur',
                    'product_data': {
                        'name': item.product.name,
                    },
                },
                'quantity': item.quantity,
            })

        # Stripe coupon
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                                name=order.coupon.code,
                                percent_off=order.discount,
                                duration='once')
            session_data['discounts'] = [{
                'coupon': stripe_coupon.id
            }]

        # create Stripe checkout session
        session = stripe.checkout.Session.create(**session_data)

        # redirect to Stripe payment form
        return redirect(session.url, code=303)

    return render(request, 'payment/payment_process.html', locals())


def payment_completed(request):
    """Payment completed view.
    """
    return render(request, 'payment/payment_completed.html')


def payment_canceled(request):
    """Payment canceled view.
    """
    return render(request, 'payment/payment_canceled.html')

templates/payment/payment_canceled.html
{% extends "base.html" %}

{% block title %}Paiement annulé{% endblock %}

{% block content %}
  <h1>Paiement annulé</h1>
  <p>Un incident s'est produit lors de votre paiement.</p>
{% endblock %}

templates/payment/payment_completed.html
{% extends "base.html" %}

{% block title %}Paiement réussit{% endblock %}

{% block content %}
  <h1>Paiement effectué</h1>
  <p>Votre paiement s'est déroulé avec succès.</p>
{% endblock %}

templates/payment/payment_process.html
{% extends "base.html" %}
{% load static %}

{% block title %}Règler la commande{% endblock %}

{% block content %}
  <h1>Récapitulatif de la commande</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Produit</th>
        <th>Prix</th>
        <th>Quantité</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.items.all %}
        <tr class="row{% cycle '1' '2' %}">
          <td>
            <img src="{% if item.product.image %}{{ item.product.image.url }}
            {% else %}{% static 'img/no_image.png' %}{% endif %}">
          </td>
          <td>{{ item.product.name }}</td>
          <td class="num">€{{ item.price }}</td>
          <td class="num">{{ item.quantity }}</td>
          <td class="num">€{{ item.get_cost }}</td>
        </tr>
      {% endfor %}

      {% if order.coupon %}
        <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="3"></td>
          <td class="num">
            €{{ order.get_total_cost_before_discount|floatformat:2 }}
          </td>
        </tr>
        <tr>
          <td>
            "{{ order.coupon.code }}" coupon
            ({{ order.discount }}% de remise)
          </td>
          <td colspan="3"></td>
          <td class="num neg">
            - €{{ order.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}

      <tr class="total">
        <td colspan="4">Total</td>
        <td class="num">€{{ order.get_total_cost|floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
  <form action="{% url 'payment:process' %}" method="post">
    <input type="submit" value="Payer">
    {% csrf_token %}
  </form>
{% endblock %}